### PR TITLE
Changes made!

### PR DESCRIPTION
**Pull request by nikiles3**

### CODE REVIEW

**Comment by cmoore24361** [comment]
I think yours looks good. Make sure to review and comment on Nishchith's pull request so you can get full credit. After y'all have done that for each other, you can merge your own commit to main.

Just a side note, do you know why you had a 3rd file added, .DS_Store? I don't think it will hurt anything, I am curious about what it is.

**Comment by nikiles3** [comment]
Christian I'm confused! Do i need to approve Nishchith's request by removing the conflict (those yellow part alone) or what do i need to do?

**Comment by nikiles3** [comment]
> I think yours looks good. Make sure to review and comment on Nishchith's pull request so you can get full credit. After y'all have done that for each other, you can merge your own commit to main.
> 
> Just a side note, do you know why you had a 3rd file added, .DS_Store? I don't think it will hurt anything, I am curious about what it is.
Christian I'm confused! Do i need to approve Nishchith's request by removing the conflict (those yellow part alone) or what do i need to do?

**Comment by NishchithAnanthaRamu** [comment]
Merged!

**Review by NishchithAnanthaRamu — COMMENTED** [review]
Reviewed and merged!

**Pull request merged**
